DECLARE
   v_user  VARCHAR2(100);
BEGIN
   SELECT user
     INTO v_user
     FROM DUAL;
  
   IF v_user != '&&1'
   THEN
     raise_application_error(-20000, 'Run as &&1; You are connected as: '||v_user);
   END IF;
     

   FOR REC 
    IN (SELECT *
          FROM USER_OBJECTS )
   LOOP
      CASE REC.OBJECT_TYPE
      WHEN 'SEQUENCE' THEN
         EXECUTE IMMEDIATE 'DROP SEQUENCE '||REC.OBJECT_NAME;
      WHEN 'TABLE' THEN
         EXECUTE IMMEDIATE 'DROP TABLE '||REC.OBJECT_NAME||' CASCADE CONSTRAINTS PURGE ';
      WHEN 'PROCEDURE' THEN
         EXECUTE IMMEDIATE 'DROP PROCEDURE '||REC.OBJECT_NAME;
      WHEN 'FUNCTION' THEN
         EXECUTE IMMEDIATE 'DROP FUNCTION '||REC.OBJECT_NAME;
      WHEN 'PACKAGE' THEN
         EXECUTE IMMEDIATE 'DROP PACKAGE '||REC.OBJECT_NAME;
      WHEN 'VIEW' THEN
         EXECUTE IMMEDIATE 'DROP VIEW '||REC.OBJECT_NAME;
      WHEN 'TYPE' THEN
         EXECUTE IMMEDIATE 'DROP TYPE '||REC.OBJECT_NAME||' FORCE';
      WHEN 'SYNONYM' THEN
         EXECUTE IMMEDIATE 'DROP SYNONYM '||REC.OBJECT_NAME;
      ELSE
         NULL;
      END CASE;
   END LOOP;

   FOR REC
    IN (SELECT *
          FROM USER_DB_LINKS )
   LOOP
      EXECUTE IMMEDIATE 'DROP DATABASE LINK "'||REC.DB_LINK||'"'; 
   END LOOP;

END;
/