CREATE TABLE APP_OBJ_NAMESPACE
(
  OBJECT_NAMESPACE     VARCHAR2(30)  NOT NULL
, DESCRIPTION          VARCHAR2(200)
--
, CONSTRAINT APP_OBJ_NAMESPACE_PK 
     PRIMARY KEY (OBJECT_NAMESPACE)
, CONSTRAINT APP_OBJ_NAMESPACE_CK01 CHECK (OBJECT_NAMESPACE = UPPER(OBJECT_NAMESPACE) )
)
;

COMMENT ON COLUMN APP_OBJ_NAMESPACE.OBJECT_NAMESPACE IS Q'{"DEFAULT":Tables, views, etc. "OTHER", "METADATA", "EXTERNAL". See: https://docs.oracle.com/cd/B19306_01/server.102/b14200/sql_elements008.htm}';