CREATE TABLE APP_OBJ_PRIVS
(
  APPLICATION_NAME  VARCHAR2(30)  NOT NULL
, OWNER             VARCHAR2(128) NOT NULL
, TYPE              VARCHAR2(24)  NOT NULL
, NAME              VARCHAR2(128) NOT NULL
, PRIVILEGE         VARCHAR2(40) NOT NULL
, IS_VALID          VARCHAR2(1)  DEFAULT 'U'     NOT NULL  --U,Y,N
, LAST_VALIDATED    DATE         DEFAULT SYSDATE NOT NULL
, CONSTRAINT APP_OBJ_PRIVS_PK 
      PRIMARY KEY (APPLICATION_NAME, OWNER, TYPE, NAME, PRIVILEGE)
, CONSTRAINT APP_OBJ_PRIVS_FK1 
      FOREIGN KEY (APPLICATION_NAME) 
         REFERENCES APPLICATION (APPLICATION_NAME)
         ON DELETE CASCADE
, CONSTRAINT APP_OBJ_PRIVS_CK1 CHECK (IS_VALID IN ('U','Y','N') ) --UNKNOWN, YES, NO
, CONSTRAINT APP_OBJ_PRIVS_CK2 CHECK (OWNER = UPPER(OWNER) )
, CONSTRAINT APP_OBJ_PRIVS_CK3 CHECK (NAME = UPPER(NAME) )
, CONSTRAINT APP_OBJ_PRIVS_CK4 
     CHECK (TYPE 
IN (
--  'DIRECTORY'
--, 'EDITION'
  'FUNCTION'
--, 'INDEXTYPE'
--, 'JOB CLASS'
--, 'OPERATOR'
, 'PACKAGE'
, 'PROCEDURE'
--, 'QUEUE'
, 'SEQUENCE'
, 'TABLE'
, 'TYPE'
--, 'UNKNOWN'
--, 'USER'
, 'VIEW'
) ) --BUGBUG - Add parent table
, CONSTRAINT APP_OBJ_PRIVS_CK5
     CHECK (PRIVILEGE 
IN (
  'DELETE'
--, 'DEQUEUE'
, 'EXECUTE'
--, 'FLASHBACK'
--, 'INHERIT PRIVILEGES'
, 'INSERT'
, 'READ'
--, 'REFERENCES'
, 'SELECT'
, 'UPDATE'
--, 'USE'
--, 'WRITE'
) ) --BUGBUG - Add parent table
) 
;

COMMENT ON TABLE  APP_OBJ_PRIVS                  IS 'Track needed/granted system privileges';
--
COMMENT ON COLUMN APP_OBJ_PRIVS.APPLICATION_NAME IS 'PK 1/5. FK to APPLICATION';
COMMENT ON COLUMN APP_OBJ_PRIVS.OWNER            IS 'PK 2/5. Object owner';
COMMENT ON COLUMN APP_OBJ_PRIVS.TYPE             IS 'PK 3/5. Object type: Package, Procedure, Sequence, Table, etc...';
COMMENT ON COLUMN APP_OBJ_PRIVS.NAME             IS 'PK 4/5. Object name';
COMMENT ON COLUMN APP_OBJ_PRIVS.PRIVILEGE        IS 'PK 5/5. Privilege: Delete, Execute, Insert, Select, etc...';
COMMENT ON COLUMN APP_OBJ_PRIVS.IS_VALID         IS 'U:Unknown, Y:Yes, N:No';
COMMENT ON COLUMN APP_OBJ_PRIVS.LAST_VALIDATED   IS 'Default SYSDATE. Last time the privilege was validated against granted privileges';
