CREATE TABLE APP_SYS_PRIVS
(
  APPLICATION_NAME  VARCHAR2(30) NOT NULL
, PRIVILEGE         VARCHAR2(40) NOT NULL
, IS_VALID          VARCHAR2(1)  DEFAULT 'U'     NOT NULL  --U,Y,N
, LAST_VALIDATED    DATE         DEFAULT SYSDATE NOT NULL
, CONSTRAINT APP_SYS_PRIVS_PK 
      PRIMARY KEY (APPLICATION_NAME, PRIVILEGE)
, CONSTRAINT APP_SYS_PRIVS_FK1 
      FOREIGN KEY (APPLICATION_NAME) 
         REFERENCES APPLICATION (APPLICATION_NAME)
         ON DELETE CASCADE
, CONSTRAINT APP_SYS_PRIVS_CK1 CHECK (IS_VALID IN ('U','Y','N') ) --UNKNOWN, YES, NO
, CONSTRAINT APP_SYS_PRIVS_CK2 
     CHECK (PRIVILEGE 
IN ( 
  'CREATE DATABASE LINK'
, 'CREATE JOB'
, 'CREATE SEQUENCE'
, 'CREATE SYNONYM'
, 'CREATE TABLE'
, 'CREATE TRIGGER'
, 'CREATE VIEW'
, 'SELECT ANY DICTIONARY'
) 
) --BUGBUG - Add parent table
) 
;

COMMENT ON TABLE  APP_SYS_PRIVS                  IS 'Track needed/granted system privileges';
--
COMMENT ON COLUMN APP_SYS_PRIVS.APPLICATION_NAME IS 'PK 1/2. FK to APPLICATION';
COMMENT ON COLUMN APP_SYS_PRIVS.PRIVILEGE        IS 'PK 2/2';
COMMENT ON COLUMN APP_SYS_PRIVS.IS_VALID         IS 'U:Unknown, Y:Yes, N:No';
COMMENT ON COLUMN APP_SYS_PRIVS.LAST_VALIDATED   IS 'Default SYSDATE. Last time the privilege was validated against granted privileges';
