ALTER TABLE APP_OBJECTS 
ADD ( MAJOR_VERSION      INTEGER      DEFAULT 0       NOT NULL 
    , MINOR_VERSION      INTEGER      DEFAULT 0       NOT NULL
    , CONSTRAINT APP_OBJECTS_CK3 CHECK (MAJOR_VERSION >= 0 AND MINOR_VERSION >= 0 )
    );

BEGIN
UPDATE APP_OBJECTS
   SET MAJOR_VERSION = TRUNC(VERSION)
     , MINOR_VERSION = TRUNC((VERSION - TRUNC(VERSION) )*10)
;
COMMIT;
END;
/

COMMENT ON COLUMN APP_OBJECTS.MAJOR_VERSION          IS 'Copied from Application.major_version';
COMMENT ON COLUMN APP_OBJECTS.MINOR_VERSION          IS 'Copied from Application.minor_version';

