CREATE TABLE APP_DEPENDENCY
(
  APPLICATION_NAME  VARCHAR2(30) NOT NULL
, DEPENDS_ON        VARCHAR2(30) NOT NULL
, VERSION_MIN       NUMBER(10,2) DEFAULT 0       NOT NULL
, VERSION_MAX       NUMBER(10,2) DEFAULT 999999  NOT NULL
, IS_VALID          VARCHAR2(1)  DEFAULT 'U'     NOT NULL  --U,Y,N
, LAST_VALIDATED    DATE         DEFAULT SYSDATE NOT NULL
--
, CONSTRAINT APP_DEPENDENCY_PK 
      PRIMARY KEY (APPLICATION_NAME, DEPENDS_ON)
, CONSTRAINT APP_DEPENDENCY_FK1 
      FOREIGN KEY (APPLICATION_NAME) 
         REFERENCES APPLICATION (APPLICATION_NAME)
         ON DELETE CASCADE
, CONSTRAINT APP_DEPENDENCY_CK1 CHECK (DEPENDS_ON = UPPER(DEPENDS_ON) )
, CONSTRAINT APP_DEPENDENCY_CK2 CHECK (VERSION_MIN >= 0)
, CONSTRAINT APP_DEPENDENCY_CK3 CHECK (VERSION_MAX <= 999999)
, CONSTRAINT APP_DEPENDENCY_CK4 CHECK (IS_VALID IN ('U','Y','N') ) --UNKNOWN, YES, NO
) 
;

COMMENT ON TABLE  APP_DEPENDENCY                  IS 'Track application dependencies';
--
COMMENT ON COLUMN APP_DEPENDENCY.APPLICATION_NAME IS 'PK 1/2. FK to APPLICATION';
COMMENT ON COLUMN APP_DEPENDENCY.DEPENDS_ON       IS 'PK 2/2';
COMMENT ON COLUMN APP_DEPENDENCY.VERSION_MIN      IS 'Default 0';
COMMENT ON COLUMN APP_DEPENDENCY.VERSION_MAX      IS 'Default 999999';
COMMENT ON COLUMN APP_DEPENDENCY.IS_VALID         IS 'U:Unknown, Y:Yes, N:No';
COMMENT ON COLUMN APP_DEPENDENCY.LAST_VALIDATED   IS 'Default SYSDATE. Last time the dependency was validated against deployed the deployed application';
