CREATE TABLE APP_OBJECT_TYPE
(
  OBJECT_TYPE          VARCHAR2(100) NOT NULL
, OBJECT_NAMESPACE     VARCHAR2(30)  NOT NULL
, SUPPORTED            VARCHAR2(1)   NOT NULL
--
, CONSTRAINT APP_OBJECT_TYPE_PK 
     PRIMARY KEY (OBJECT_TYPE)
, CONSTRAINT APP_OBJECT_TYPE_UK01
     UNIQUE (OBJECT_TYPE, OBJECT_NAMESPACE)
, CONSTRAINT APP_OBJECT_TYPE_FK01 
     FOREIGN KEY (OBJECT_NAMESPACE)
     REFERENCES APP_OBJ_NAMESPACE (OBJECT_NAMESPACE)
     --ON DELETE CASCADE
, CONSTRAINT APP_OBJECT_TYPE_CK01 CHECK (OBJECT_TYPE = UPPER(OBJECT_TYPE) )
, CONSTRAINT APP_OBJECT_TYPE_CK02 CHECK (SUPPORTED IN ('Y','N') )
)
;

COMMENT ON TABLE  APP_OBJECT_TYPE IS 'Object types recognized by the system. All Oracle object types plus: METADATA, EXTERNAL';
COMMENT ON COLUMN APP_OBJECT_TYPE.OBJECT_TYPE IS Q'{We define the following object types:
  METADATA - Used for data contained within tables. The hash query must be user-defined.
  EXTERNAL - Objects external to the database such as scripts.

Oracle (as of 12c) defines the following object types:
  CLUSTER
  CONSUMER GROUP
  CONTAINER
  CONTEXT
  DATABASE LINK
  DESTINATION
  DIRECTORY
  EDITION
  EVALUATION CONTEXT
  FUNCTION
  INDEX
  INDEX PARTITION
  INDEXTYPE
  JOB
  JOB CLASS
  LIBRARY
  LOB
  LOB PARTITION
  OPERATOR
  PACKAGE
  PACKAGE BODY
  PROCEDURE
  PROGRAM
  QUEUE
  RESOURCE PLAN
  RULE
  RULE SET
  SCHEDULE
  SCHEDULER GROUP
  SEQUENCE
  SYNONYM
  TABLE
  TABLE PARTITION
  TABLE SUBPARTITION
  TRIGGER
  TYPE
  TYPE BODY
  UNDEFINED
  UNIFIED AUDIT POLICY
  VIEW
  WINDOW
  XML SCHEMA
}';

COMMENT ON COLUMN APP_OBJECT_TYPE.SUPPORTED IS 'Is the object type supported by the application? Y:Yes, N:No.';
