CREATE TABLE APP_DEPLOY_PROVENANCE_PENDING
(
  APPLICATION_NAME          VARCHAR2(30)   NOT NULL
, MAJOR_VERSION             INTEGER        NOT NULL
, MINOR_VERSION             INTEGER        NOT NULL
, PATCH_VERSION             INTEGER        NOT NULL
, DEPLOY_TYPE               VARCHAR2(1)    NOT NULL
, DEPLOY_COMMIT_HASH        VARCHAR2(40)   DEFAULT '0000000000000000000000000000000000000000' NOT NULL
, ARTIFACT_URI              VARCHAR2(4000)
, ARTIFACT_CHECKSUM         VARCHAR2(128)
, ARTIFACT_CHECKSUM_ALG     VARCHAR2(30)
, ARTIFACT_FILE_NAME        VARCHAR2(512)
, ARTIFACT_REPOSITORY_TYPE  VARCHAR2(30)
, ARTIFACT_GROUP_ID         VARCHAR2(255)
, ARTIFACT_ID               VARCHAR2(255)
, ARTIFACT_VERSION          VARCHAR2(255)
, ARTIFACT_CLASSIFIER       VARCHAR2(255)
, ARTIFACT_EXTENSION        VARCHAR2(30)
, PACKAGE_COORDINATE        VARCHAR2(1000)
, SOURCE_REPOSITORY_URL     VARCHAR2(4000)
, SOURCE_COMMIT_HASH        VARCHAR2(40)
, SOURCE_PATH               VARCHAR2(4000)
, BUILD_ID                  VARCHAR2(255)
, BUILD_URL                 VARCHAR2(4000)
, BUILD_TIME                VARCHAR2(64)
, BUILD_METADATA_JSON       CLOB
, STAGED_TS                 DATE           DEFAULT SYSDATE NOT NULL
, CONSTRAINT APP_DEPLOY_PROV_PENDING_UK1
      UNIQUE (APPLICATION_NAME, MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION, DEPLOY_TYPE, DEPLOY_COMMIT_HASH)
, CONSTRAINT APP_DEPLOY_PROV_PENDING_CK1
      CHECK (APPLICATION_NAME = UPPER(APPLICATION_NAME))
, CONSTRAINT APP_DEPLOY_PROV_PENDING_CK2 CHECK (MAJOR_VERSION >= 0)
, CONSTRAINT APP_DEPLOY_PROV_PENDING_CK3 CHECK (MINOR_VERSION >= 0)
, CONSTRAINT APP_DEPLOY_PROV_PENDING_CK4 CHECK (PATCH_VERSION >= 0)
, CONSTRAINT APP_DEPLOY_PROV_PENDING_CK5 CHECK (DEPLOY_TYPE IN ('I','V', 'M', 'P') )
)
;

COMMENT ON TABLE  APP_DEPLOY_PROVENANCE_PENDING IS 'Stages artifact and build provenance before the application deployment script calls begin_deployment_p';
--
COMMENT ON COLUMN APP_DEPLOY_PROVENANCE_PENDING.APPLICATION_NAME         IS 'Application whose deployment provenance is staged';
COMMENT ON COLUMN APP_DEPLOY_PROVENANCE_PENDING.MAJOR_VERSION            IS 'Target major version';
COMMENT ON COLUMN APP_DEPLOY_PROVENANCE_PENDING.MINOR_VERSION            IS 'Target minor version';
COMMENT ON COLUMN APP_DEPLOY_PROVENANCE_PENDING.PATCH_VERSION            IS 'Target patch version';
COMMENT ON COLUMN APP_DEPLOY_PROVENANCE_PENDING.DEPLOY_TYPE              IS 'I:Initial; V:major Version, M:Minor, P:Patch';
COMMENT ON COLUMN APP_DEPLOY_PROVENANCE_PENDING.DEPLOY_COMMIT_HASH       IS 'Repository commit hash expected by the deployment script';
COMMENT ON COLUMN APP_DEPLOY_PROVENANCE_PENDING.ARTIFACT_URI             IS 'Resolved artifact URL, repository URL, or local path used for deployment';
COMMENT ON COLUMN APP_DEPLOY_PROVENANCE_PENDING.ARTIFACT_CHECKSUM        IS 'Checksum of the exact artifact bytes used for deployment';
COMMENT ON COLUMN APP_DEPLOY_PROVENANCE_PENDING.ARTIFACT_CHECKSUM_ALG    IS 'Checksum algorithm, such as SHA-256';
COMMENT ON COLUMN APP_DEPLOY_PROVENANCE_PENDING.ARTIFACT_FILE_NAME       IS 'Resolved artifact file name, such as the exact ZIP name';
COMMENT ON COLUMN APP_DEPLOY_PROVENANCE_PENDING.ARTIFACT_REPOSITORY_TYPE IS 'Artifact repository type, such as maven, file, github, or manual';
COMMENT ON COLUMN APP_DEPLOY_PROVENANCE_PENDING.ARTIFACT_GROUP_ID        IS 'Package repository group id when available';
COMMENT ON COLUMN APP_DEPLOY_PROVENANCE_PENDING.ARTIFACT_ID              IS 'Package repository artifact id when available';
COMMENT ON COLUMN APP_DEPLOY_PROVENANCE_PENDING.ARTIFACT_VERSION         IS 'Package repository artifact version when available';
COMMENT ON COLUMN APP_DEPLOY_PROVENANCE_PENDING.ARTIFACT_CLASSIFIER      IS 'Package repository classifier when available';
COMMENT ON COLUMN APP_DEPLOY_PROVENANCE_PENDING.ARTIFACT_EXTENSION       IS 'Package repository extension when available';
COMMENT ON COLUMN APP_DEPLOY_PROVENANCE_PENDING.PACKAGE_COORDINATE       IS 'Resolved package coordinate as provided by deployment tooling';
COMMENT ON COLUMN APP_DEPLOY_PROVENANCE_PENDING.SOURCE_REPOSITORY_URL    IS 'Source repository URL associated with the artifact';
COMMENT ON COLUMN APP_DEPLOY_PROVENANCE_PENDING.SOURCE_COMMIT_HASH       IS 'Source commit hash associated with the artifact';
COMMENT ON COLUMN APP_DEPLOY_PROVENANCE_PENDING.SOURCE_PATH              IS 'Optional local source path used by the deployment tool';
COMMENT ON COLUMN APP_DEPLOY_PROVENANCE_PENDING.BUILD_ID                 IS 'External build identifier';
COMMENT ON COLUMN APP_DEPLOY_PROVENANCE_PENDING.BUILD_URL                IS 'External build URL';
COMMENT ON COLUMN APP_DEPLOY_PROVENANCE_PENDING.BUILD_TIME               IS 'External build timestamp as provided by the artifact or deployment tool';
COMMENT ON COLUMN APP_DEPLOY_PROVENANCE_PENDING.BUILD_METADATA_JSON      IS 'Free-form build metadata captured as JSON text';
COMMENT ON COLUMN APP_DEPLOY_PROVENANCE_PENDING.STAGED_TS                IS 'Timestamp when provenance was staged';
