CREATE TABLE APP_OBJECT_METADATA
(
  OBJECT_NAME           VARCHAR2(128) NOT NULL
, OBJECT_NAMESPACE      VARCHAR2(30)  NOT NULL
, OBJECT_TYPE           VARCHAR2(100) NOT NULL
, APPLICATION_NAME      VARCHAR2(30)  NOT NULL
, DISCRIMINATOR_COL     VARCHAR2(128) DEFAULT 'NONE'     NOT NULL
, DISCRIMINATOR_VAL     VARCHAR2(200) DEFAULT 'NONE'     NOT NULL
, LAST_UPDATE           DATE          DEFAULT SYSDATE    NOT NULL
, VERSION               VARCHAR2(14)
, DML_OVERRIDE_PROC     VARCHAR2(200)
--
, CONSTRAINT APP_OBJECT_METADATA_PK 
     PRIMARY KEY (OBJECT_NAME, OBJECT_NAMESPACE, DISCRIMINATOR_COL, DISCRIMINATOR_VAL)
, CONSTRAINT APP_OBJECT_METADATA_FK1 
     FOREIGN KEY (OBJECT_NAME, OBJECT_NAMESPACE) 
        REFERENCES APP_OBJECTS (OBJECT_NAME, OBJECT_NAMESPACE)
           ON DELETE CASCADE
, CONSTRAINT APP_OBJECT_METADATA_FK2 
     FOREIGN KEY (APPLICATION_NAME) 
        REFERENCES APPLICATION (APPLICATION_NAME)
           ON DELETE CASCADE
, CONSTRAINT APP_OBJECT_METADATA_CK1 CHECK (DISCRIMINATOR_COL = UPPER(DISCRIMINATOR_COL) ) 
, CONSTRAINT APP_OBJECT_METADATA_CK2 CHECK ( (DISCRIMINATOR_COL = 'NONE' AND DISCRIMINATOR_VAL = 'NONE') OR DISCRIMINATOR_COL != 'NONE' ) 
) 
;

COMMENT ON TABLE  APP_OBJECT_METADATA                  IS 'Track object metadata and provide for automatic deletion';
--
COMMENT ON COLUMN APP_OBJECT_METADATA.OBJECT_NAME       IS 'PK 1/6. FK to APP_OBJECTS';
COMMENT ON COLUMN APP_OBJECT_METADATA.OBJECT_NAMESPACE  IS 'PK 2/6. FK to APP_OBJECTS';
COMMENT ON COLUMN APP_OBJECT_METADATA.OBJECT_TYPE       IS 'Denormalized from APP_OBJECTS';
COMMENT ON COLUMN APP_OBJECT_METADATA.APPLICATION_NAME  IS 'FK to APPLICATION. The application that owns the metadata';
COMMENT ON COLUMN APP_OBJECT_METADATA.DISCRIMINATOR_COL IS 'PK 3/6. "NONE" if referring to the main object; Otherwise, the upper-case column name that holds the discriminator value';
COMMENT ON COLUMN APP_OBJECT_METADATA.DISCRIMINATOR_VAL IS 'PK 4/6. "NONE" if referring to the main object; Otherwise, the identifier associated with the segregation';
COMMENT ON COLUMN APP_OBJECT_METADATA.LAST_UPDATE       IS 'The timestamp the row was inserted/updated';
COMMENT ON COLUMN APP_OBJECT_METADATA.VERSION           IS 'major.minor.patch';
COMMENT ON COLUMN APP_OBJECT_METADATA.DML_OVERRIDE_PROC IS 'A procedure to be called instead of deleting rows directly';
