CREATE TABLE APPLICATION
(
  APPLICATION_NAME   VARCHAR2(30) NOT NULL
, MAJOR_VERSION      INTEGER      DEFAULT 0       NOT NULL 
, MINOR_VERSION      INTEGER      DEFAULT 1       NOT NULL
, PATCH_VERSION      INTEGER      DEFAULT 0       NOT NULL
, PRE_RELEASE        VARCHAR(30)
, BUILD              VARCHAR(30)
, DEPLOY_TYPE        VARCHAR2(1)  DEFAULT 'I'     NOT NULL
, DEPLOY_STATUS      VARCHAR2(1)  DEFAULT 'R'     NOT NULL
, DEPLOY_COMMIT_HASH VARCHAR2(40) DEFAULT '0000000000000000000000000000000000000000' NOT NULL
, DEPLOY_BEGIN       DATE         DEFAULT SYSDATE NOT NULL
, DEPLOY_END         DATE         DEFAULT NULL
, CONSTRAINT APPLICATION_PK 
      PRIMARY KEY (APPLICATION_NAME)
, CONSTRAINT APPLICATION_CK1 CHECK (APPLICATION_NAME = UPPER(APPLICATION_NAME) )
, CONSTRAINT APPLICATION_CK2 CHECK (MAJOR_VERSION >= 0)
, CONSTRAINT APPLICATION_CK3 CHECK (MINOR_VERSION >= 0)
, CONSTRAINT APPLICATION_CK4 CHECK (PATCH_VERSION >= 0)
, CONSTRAINT APPLICATION_CK5 CHECK (DEPLOY_TYPE IN ('I','V', 'M', 'P') )       --INITIAL, major Version, MINOR, PATCH
, CONSTRAINT APPLICATION_CK6 CHECK (DEPLOY_STATUS IN ('R','C','F') ) --RUNNING, COMPLETE, FAIL
, CONSTRAINT APPLICATION_CK7 CHECK (   (DEPLOY_END IS NULL) 
                                    OR (DEPLOY_END IS NOT NULL AND DEPLOY_STATUS != 'R') )
) 
;

COMMENT ON TABLE  APPLICATION                  IS 'Keep track of deployed applications';
--
COMMENT ON COLUMN APPLICATION.APPLICATION_NAME IS 'PK 1/1';
--COMMENT ON COLUMN APPLICATION.VERSION          IS 'Default 0.1';
COMMENT ON COLUMN APPLICATION.MAJOR_VERSION    IS 'Default 0. See http://semver.org';
COMMENT ON COLUMN APPLICATION.MINOR_VERSION    IS 'Default 1';
COMMENT ON COLUMN APPLICATION.PATCH_VERSION    IS 'Default 0';
COMMENT ON COLUMN APPLICATION.DEPLOY_TYPE      IS 'I:Initial; V:major Version, M:Minor, P:Patch';
COMMENT ON COLUMN APPLICATION.DEPLOY_STATUS    IS 'R:Running; C:Complete; F:Fail';
COMMENT ON COLUMN APPLICATION.DEPLOY_COMMIT_HASH IS 'Repository commit hash at application root at time of deploy';
COMMENT ON COLUMN APPLICATION.DEPLOY_BEGIN     IS 'Default SYSDATE';
COMMENT ON COLUMN APPLICATION.DEPLOY_END       IS 'The time the status changes from R to C or F';
