BEGIN
   FOR REC IN 
   (
   SELECT *
     FROM USER_CONSTRAINTS
    WHERE TABLE_NAME = 'APPLICATION'
      AND CONSTRAINT_TYPE = 'C'
      AND CONSTRAINT_NAME NOT LIKE 'SYS_%'
   )
   LOOP
      EXECUTE IMMEDIATE 'ALTER TABLE '||REC.TABLE_NAME||' DROP CONSTRAINT '||REC.CONSTRAINT_NAME;
   END LOOP;
END;
/

ALTER TABLE APPLICATION 
ADD ( MAJOR_VERSION      INTEGER      DEFAULT 0       NOT NULL 
    , MINOR_VERSION      INTEGER      DEFAULT 1       NOT NULL
    , PATCH_VERSION      INTEGER      DEFAULT 0       NOT NULL
    , PRE_RELEASE        VARCHAR(30)
    , BUILD              VARCHAR(30) 
    )
;

BEGIN
UPDATE APPLICATION
SET MAJOR_VERSION = TRUNC(VERSION)
  , MINOR_VERSION = TRUNC((VERSION - TRUNC(VERSION) )*10)
;
COMMIT;
END;
/

ALTER TABLE APPLICATION ADD 
(
  CONSTRAINT APPLICATION_CK1 CHECK (APPLICATION_NAME = UPPER(APPLICATION_NAME) )
, CONSTRAINT APPLICATION_CK2 CHECK (MAJOR_VERSION >= 0)
, CONSTRAINT APPLICATION_CK3 CHECK (MINOR_VERSION >= 0)
, CONSTRAINT APPLICATION_CK4 CHECK (PATCH_VERSION >= 0)
, CONSTRAINT APPLICATION_CK5 CHECK (DEPLOY_TYPE IN ('I','V', 'M', 'P') )       --INITIAL, major Version, MINOR, PATCH
, CONSTRAINT APPLICATION_CK6 CHECK (DEPLOY_STATUS IN ('R','C','F') ) --RUNNING, COMPLETE, FAIL
, CONSTRAINT APPLICATION_CK7 CHECK (   (DEPLOY_END IS NULL) 
                                    OR (DEPLOY_END IS NOT NULL AND DEPLOY_STATUS != 'R') )
)
;

COMMENT ON COLUMN APPLICATION.MAJOR_VERSION    IS 'Default 0. See http://semver.org';
COMMENT ON COLUMN APPLICATION.MINOR_VERSION    IS 'Default 1';
COMMENT ON COLUMN APPLICATION.PATCH_VERSION    IS 'Default 0';
COMMENT ON COLUMN APPLICATION.DEPLOY_TYPE      IS 'I:Initial; V:major Version, M:Minor, P:Patch';

