CREATE TABLE TRACE_LOG
(
  INSTANCE_ID       NUMBER(2,0)   NOT NULL
, OBJECT_NAME       VARCHAR2(30)  NOT NULL
, PROCEDURE_NAME    VARCHAR2(30)  
, EVENT             VARCHAR2(100) NOT NULL
, EVENT_TIMESTAMP   TIMESTAMP(6)  NOT NULL
, TIME_WAITED_MICRO NUMBER        NOT NULL
, LOAD              NUMBER
, CONTEXT           VARCHAR2(100)
, CONSTRAINT TRACE_LOG_CK1 CHECK ( OBJECT_NAME = UPPER(OBJECT_NAME) )
, CONSTRAINT TRACE_LOG_CK2 CHECK ( PROCEDURE_NAME = UPPER(PROCEDURE_NAME) )
, CONSTRAINT TRACE_LOG_CK3 CHECK ( EVENT = LOWER(EVENT) )
, CONSTRAINT TRACE_LOG_CK4 CHECK ( TIME_WAITED_MICRO >= 0 )
)
NOLOGGING
PARTITION BY RANGE (EVENT_TIMESTAMP) 
INTERVAL ( NUMTOYMINTERVAL(1, 'MONTH') )
 (
 PARTITION "P0" VALUES LESS THAN ( TO_DATE('2020-01-01','YYYY-MM-DD') )
 ) 
;

COMMENT ON TABLE TRACE_LOG IS '';

COMMENT ON COLUMN TRACE_LOG.INSTANCE_ID IS 'The RAC instance ID';
COMMENT ON COLUMN TRACE_LOG.OBJECT_NAME IS 'Upper case name of object logging the event. Package name if exists, otherwise procedure/function name';
COMMENT ON COLUMN TRACE_LOG.PROCEDURE_NAME IS 'Upper case name of packaged procedure. If a standalone PROCEDURE or FUNCTION, this should be NULL';
COMMENT ON COLUMN TRACE_LOG.EVENT IS 'Lower case event name';
COMMENT ON COLUMN TRACE_LOG.EVENT_TIMESTAMP IS 'Instant the event was logged';
COMMENT ON COLUMN TRACE_LOG.TIME_WAITED_MICRO IS 'Amount of time event took (user reported)';
COMMENT ON COLUMN TRACE_LOG.LOAD IS 'System load at instant event was logged';
COMMENT ON COLUMN TRACE_LOG.CONTEXT IS 'Optional context to assist with correlating data';
